### ISSUE TITLE
Achieving save_all query speed for find, and find_one.

### ISSUE THREAD

**Issue by bimarifin** [art049/odmantic#174] opened 2021-08-20 01:52 UTC
Hi Guys, and kudos to developers 👍 

when working with > 200 millions data, it seems AIOEngine find_one, and find, slowing speed much more.

find and find_one query showing by Current Network Requests on mongo monitor was: 300 - 400 Requests per seconds. while just one save_all can achieve 5k - 15k requests per seconds.

have tips for this? been trying about asyncio efficiency (building lists of query), slimmer methods, threading and collection indexing, nothing so works after while.

or maybe a new feature to plan? 🍡

**Comment by art049** [comment] 2022-08-31 22:55
Hey, yes totally. This is because find and find_one are using the `aggregate` method to fetch all the references eagerly.
#250 will add the possibility to define lazy references and should drastically improve the query speed :)

Closing this since it's a duplicate of #130

**Closed by art049** 2022-08-31 22:55 UTC
Labels: enhancement
