### ISSUE TITLE
After resolving python circular import error, docs not working.

### ISSUE THREAD

**Issue by SSaeedHoseini** [art049/odmantic#181] opened 2021-09-12 06:42 UTC
Using odmantic 0.3.5 with this model:

person.py
```
from __future__ import annotations

from typing import Optional

from odmantic import Field , Model
# from pydantic import Field, BaseModel as Model <--  docs work fine but odmantic raise error 


class Person(Model):
    name: Optional[str] = Field(None, <-- some extra options --> )
    rooms: "Optional[Room]" = Field(None, <-- some extra options --> )


from ..models.room import Room  # nopep8
Person.update_forward_refs()

```

room.py
```
from __future__ import annotations

from typing import Optional

from odmantic import Field , Model
# from pydantic import Field, BaseModel as Model <--  docs work fine but odmantic raise error 


class Room(Model):
    name: Optional[str] = Field(None, <-- some extra options --> )
    persons: "Optional[Person]" = Field(None, <-- some extra options --> )


from ..models.person import Person  # nopep8
Room.update_forward_refs()

```
### Current Behavior

this [project](https://github.com/SSaeedHoseini/odmantic-crash-docs-example) reproduce the bug, you can execute ./run.sh and open the http://127.0.0.1:8000/docs#/

### Expected behavior

show docs.
![image](https://user-images.githubusercontent.com/47109202/132976341-968a3bdc-6181-4f14-97a1-e549ee87638d.png)

### Environment

- ODMantic version: 0.3.5
- MongoDB version: 4.4.8
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`):

```
pydantic version: 1.8.2
pydantic compiled: True
install path: /xxx/lib/python3.9/site-packages/pydantic
python version: 3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0]
platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.33
optional deps. installed: ['dotenv', 'typing-extensions']
```

**Additional context**
error raised from when open the docs:
```
Traceback (most recent call last):
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 387, in get_openapi
    definitions = get_model_definitions(
  File "/xxx/odmantic-crash-docs-example/.venv/lib/python3.9/site-packages/fastapi/utils.py", line 24, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 839, in pydantic.schema.field_singleton_schema
  File "/usr/lib/python3.9/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by art049** [comment] 2022-08-23 15:15
It seems you're trying to work with References without directly specifying them.
You should take a look at https://art049.github.io/odmantic/modeling/#referenced-models or use Embedded models instead.
Circular references are not supported yet since references are all resolved by design.

**Closed by art049** 2022-08-23 15:15 UTC
Labels: bug
